### ISSUE TITLE
Rails in production - getting "Errno::ENOENT: No such file or directory @ rb_sysopen - public/uploads/cache/…"

### ISSUE THREAD

**Issue by R4ttlesnake** [janko-m/shrine#151]
Hi,
I'm using Shrine to upload Images and Videos to my Rails application and they are being processed in the background via Sidekiq. In Development everything worked really well, but in Production I get this error for the cache folder from my Sidekiq Monitor:

`Errno::ENOENT: No such file or directory @ rb_sysopen - public/uploads/cache/message/image/2e021ba0c168ef46e9ff1d8fbde25d6e.png` 

Normally I'm using jQuery fileupload to upload and post the record, but also with a basic post submit without jQuery this error happens. This error happens most of the time, so sometimes, the file is being processed and everything works out. How can it happen that in production, I get this error?

EDIT: When I ssh into my production server and check the paths mentioned in the errors, the files are actually there.

My shrine initializer:

```
require "shrine"
require "shrine/storage/file_system"
require "shrine/storage/memory" if Rails.env.test?

if Rails.env.development? || Rails.env.production?

  Shrine.storages = {
    cache: Shrine::Storage::FileSystem.new("public", prefix: "uploads/cache"),
    store: Shrine::Storage::FileSystem.new("public", prefix: "uploads/store"),
  }
  
elsif Rails.env.test?

  Shrine.storages = {
    cache: Shrine::Storage::Memory.new,
    store: Shrine::Storage::Memory.new,
  }

end

Shrine.plugin :activerecord
Shrine.plugin :logging, logger: Rails.logger
Shrine.plugin :direct_upload
Shrine.plugin :hooks
Shrine.plugin :backgrounding

# execute file promotion / deletion in background
Shrine::Attacher.promote { |data| PromoteJob.perform_async(data) }
Shrine::Attacher.delete { |data| DeleteJob.perform_async(data) }

```

My uploaders:

```
require "image_processing/mini_magick"

class BaseUploader < Shrine
  include ImageProcessing::MiniMagick

  plugin :pretty_location
  plugin :delete_raw
  plugin :delete_promoted
  plugin :cached_attachment_data
  plugin :determine_mime_type
  plugin :validation_helpers
  plugin :processing
  plugin :versions

  def preprocess(image)
    convert(image, "jpg") do |cmd|
      cmd.auto_orient
      cmd.quality 82
      cmd.strip
    end
  end

  def blur(image)
    convert(image, "jpg") do |cmd|
      cmd.blur "0x8"
      cmd.resize "5120x2880"
    end
  end
end
```

```
class ImageUploader < BaseUploader

  # validate images
  Attacher.validate do
    validate_mime_type_inclusion %w[image/jpeg image/png image/gif], 
                            message: "You can only upload image files of the type .jpg, .jpeg, .gif or .png."
    validate_max_size 5.megabyte, 
                            message: "You can not upload images bigger than 5MB."
  end

  # process / versions
  if Rails.env.development? || Rails.env.production?

    # processing and versions
    …
  else
    
    # in test do no processing
    …
  end
end
```
My model:

```
class Message < ApplicationRecord
  belongs_to :user
  scope :published, -> { where(processing: false) }
  scope :processing, -> { where(processing: true) }

  # uploaders
  include ImageUploader[:image]
  include VideoUploader[:video]

  …
end
```

Thanks for any advice!

**Comment by janko-m** [comment]
Could you describe more your production environment (e.g. are you using more than one server, are the Sidekiq jobs executed on the same servers as your app etc)?

I'm wondering if it isn't a filesystem syncing bug. Firstly, when you write to files in Ruby, Ruby keeps an internal buffer so that it doesn't flush to disk on each write. Secondly, the operating system itself usually has its own buffer as well. As far as I know, there are two ways to sync in Ruby; one is setting `File#sync` to `true` when opening the file (this will essentially disable Ruby's buffer), and calling `File#fsync` after writing, which actually tells the operating system to flush its buffer. However, my assumption was that flushing automatically happens once you close the file (at least Ruby's buffer), since you delete the file descriptor.

Could you check whether the cached file exists immediately after uploading?

```rb
class Message < ApplicationRecord
  # ...

  def image=(value)
    super
    puts image.exists? if image
  end

  def video=(value)
    super
    puts video.exists? if video
  end
end
```

If it outputs `true`, but the Sidekiq jobs still aren't able to find them, then something else is wrong, the files are not found for some other reason. But if they output `false`, then it's most likely a syncing issue and should definitely be fixed on the Shrine side.

**Comment by R4ttlesnake** [comment]
Hi, thanks for the advice so far.

First of all, I checked the functionality without backgrounding the processing via Sidekiq and everything works well. With backgrounding, the `image=(value) method` outputs `true` for `image.exists?`. So the cached file seem to be present immediately after uploading.

I'm running everything one simple server with Ubuntu 16.04, so the Sidekiq jobs are executed on the same server as my app. Sidekiq and Redis are initiated on server boot via systemd. Besides that everything is standard configuration and I made no specific setups.

What surprised me is also that rarely the file passes through, is being processed by Sidekiq and everything works out..

**Comment by janko-m** [comment]
@R4ttlesnake That's really strange. Sidekiq worker classes don't have any specific configuration? One other thing to try is removing the `delete_promoted` plugin, perhaps it's somehow deleting the cached files when it shouldn't. Could you also post processing code? Finally, could you post a backtrace of the `Errno::ENOENT` error, so that I can see where it's coming from?

**Comment by R4ttlesnake** [comment]
Thanks so far. Without the `delete_promoted` plugin, I get the same error. Also I tried rescheduling the `PromoteJob` to perform 2 minutes later than the job was called, again the same error.

Processing from base_uploader.rb:

```
def preprocess(image)
  convert(image, "jpg") do |cmd|
    cmd.auto_orient
    cmd.quality 82
    cmd.strip
  end
end

def blur(image)
  convert(image, "jpg") do |cmd|
    cmd.blur "0x8"
    cmd.resize "5120x2880"
  end
end
```
Processing from image_uploader.rb:
```
if Rails.env.development? || Rails.env.production?

  process(:store) do |io, context|

    base = preprocess(io.download)

    large_2x = resize_to_limit(base, 5120, 2880)
    large = resize_to_limit(large_2x, 2560, 1440)

    medium_2x = resize_to_limit(large_2x, 2880, 1800)
    medium = resize_to_limit(large, 1440, 900)

    small_2x = resize_to_limit(medium_2x, 2048, 1536)
    small = resize_to_limit(medium, 1024, 768)

    mobile_2x = resize_to_limit(small_2x, 1334, 1334)
    mobile = resize_to_limit(small, 667, 667)

    blur = blur(medium)

    { mobile: mobile, mobile_2x: mobile_2x, 
      small: small, small_2x: small_2x, 
      medium: medium, medium_2x: medium_2x, 
      large: large, large_2x: large_2x, 
      blur: blur }
  end

else
  
  def process(io, context)

    if context[:action] == :store

      # "fake" versions
      { mobile: io, mobile_2x: io.download, 
        small: io.download, small_2x: io.download, 
        medium: io.download, medium_2x: io.download, 
        large: io.download, large_2x: io.download,
        blur: io.download }
    end
  end
end
```

Sidekiq error from syslog:
```
Mar 29 08:58:47 Almoist sidekiq[1306]: 2017-03-29T08:58:47.803Z 1306 TID-gq8sx6kn0 PromoteJob JID-b101330907a4c82192788fcb INFO: start
Mar 29 08:58:47 Almoist sidekiq[1306]: 2017-03-29T08:58:47.821Z 1306 TID-gq8sx6kn0 PromoteJob JID-b101330907a4c82192788fcb INFO: fail: 0.018 sec
Mar 29 08:58:47 Almoist sidekiq[1306]: 2017-03-29T08:58:47.823Z 1306 TID-gq8sx6kn0 WARN: {"context":"Job raised exception","job":{"class":"PromoteJob","args":[{"attachment":"{\"id\":\"e5eacf3244bd8ffd91f2c876b6102a1e.jpeg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"font1.jpeg\",\"size\":281094,\"mime_type\":\"image/jpeg\"}}","record":["Message","30"],"name":"image","shrine_class":"ImageUploader","action":"store","phase":"store"}],"retry":true,"queue":"default","jid":"b101330907a4c82192788fcb","created_at":1490777678.5545304,"enqueued_at":1490777927.8021653,"error_message":"No such file or directory @ rb_sysopen - public/uploads/cache/e5eacf3244bd8ffd91f2c876b6102a1e.jpeg","error_class":"Errno::ENOENT","failed_at":1490777817.1959364,"retry_count":2,"retried_at":1490777927.8223574},"jobstr":"{\"class\":\"PromoteJob\",\"args\":[{\"attachment\":\"{\\\"id\\\":\\\"e5eacf3244bd8ffd91f2c876b6102a1e.jpeg\\\",\\\"storage\\\":\\\"cache\\\",\\\"metadata\\\":{\\\"filename\\\":\\\"font1.jpeg\\\",\\\"size\\\":281094,\\\"mime_type\\\":\\\"image/jpeg\\\"}}\",\"record\":[\"Message\",\"30\"],\"name\":\"image\",\"shrine_class\":\"ImageUploader\",\"action\":\"store\",\"phase\":\"store\"}],\"retry\":true,\"queue\":\"default\",\"jid\":\"b101330907a4c82192788fcb\",\"created_at\":1490777678.5545304,\"enqueued_at\":1490777927.8021653,\"error_message\":\"No such file or directory @ rb_sysopen - public/uploads/cache/e5eacf3244bd8ffd91f2c876b6102a1e.jpeg\",\"error_class\":\"Errno::ENOENT\",\"failed_at\":1490777817.1959364,\"retry_count\":1,\"retried_at\":1490777879.4835765}"}
Mar 29 08:58:47 Almoist sidekiq[1306]: 2017-03-29T08:58:47.825Z 1306 TID-gq8sx6kn0 WARN: Errno::ENOENT: No such file or directory @ rb_sysopen - public/uploads/cache/e5eacf3244bd8ffd91f2c876b6102a1e.jpeg
Mar 29 08:58:47 Almoist sidekiq[1306]: 2017-03-29T08:58:47.825Z 1306 TID-gq8sx6kn0 WARN: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/storage/file_system.rb:144:in `initialize'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/storage/file_system.rb:144:in `open'
Mar 29 08:58:47 Almoist sidekiq[1306]: message repeated 2 times: [ /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/storage/file_system.rb:144:in `open']
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine.rb:765:in `open'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine.rb:779:in `download'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/releases/20170325145146/app/uploaders/image_uploader.rb:16:in `block in <class:ImageUploader>'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/processing.rb:69:in `instance_exec'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/processing.rb:69:in `block in process'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/processing.rb:68:in `each'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/processing.rb:68:in `inject'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/processing.rb:68:in `process'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine.rb:337:in `processed'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/hooks.rb:75:in `block in processed'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/hooks.rb:82:in `around_process'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/hooks.rb:75:in `processed'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/logging.rb:96:in `block in processed'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/logging.rb:101:in `block in log'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/logging.rb:161:in `block in benchmark'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/.rbenv/versions/2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/logging.rb:161:in `benchmark'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/logging.rb:101:in `log'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/logging.rb:96:in `processed'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine.rb:205:in `upload'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/hooks.rb:56:in `block in upload'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/hooks.rb:62:in `around_upload'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/hooks.rb:56:in `upload'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine.rb:611:in `store!'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine.rb:544:in `promote'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/delete_promoted.rb:12:in `promote'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/shrine-2.5.0/lib/shrine/plugins/backgrounding.rb:133:in `promote'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/releases/20170325145146/app/jobs/promote_job.rb:7:in `perform'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/rails.rb:90:in `block in call'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/rails.rb:89:in `call'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
Mar 29 08:58:47 Almoist sidekiq[1306]: /home/deploy/almoist_chat_app/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
Mar 29 09:00:22 Almoist redis-server[1324]: 1324:M 29 Mar 09:00:22.022 * 10 changes in 300 seconds. Saving...
Mar 29 09:00:22 Almoist redis-server[1324]: 1324:M 29 Mar 09:00:22.024 * Background saving started by pid 3987
Mar 29 09:00:22 Almoist redis-server[1324]: 3987:C 29 Mar 09:00:22.030 * DB saved on disk
Mar 29 09:00:22 Almoist redis-server[1324]: 3987:C 29 Mar 09:00:22.033 * RDB: 0 MB of memory used by copy-on-write
Mar 29 09:00:22 Almoist redis-server[1324]: 1324:M 29 Mar 09:00:22.125 * Background saving terminated with success
Mar 29 09:02:05 Almoist kernel: [ 1616.253052] ip_tables: (C) 2000-2006 Netfilter Core Team
```

**Comment by janko-m** [comment]
Ok, from what I can see, the error is happening on this line, as expected:

```
if Rails.env.development? || Rails.env.production?
  process(:store) do |io, context|
    base = preprocess(io.download) # <======
    # ...
else
  # ...
end
```

However, I still have no idea why would Sidekiq workers not be able to find the cached file *sometimes*. Another thing that comes to mind is to try to setup the FileSystem storage to use full paths instead of relative:

```rb
  Shrine.storages = {
    cache: Shrine::Storage::FileSystem.new(Rails.root.join("public"), prefix: "uploads/cache"),
    store: Shrine::Storage::FileSystem.new(Rails.root.join("public"), prefix: "uploads/store"),
  }
```

Another way to check whether Shrine is at any point deleting the cached file is to override `Shrine::Storage::FileSystem#delete` and add a `puts` statement there.

```rb
  Shrine.storages = {
    cache: Shrine::Storage::FileSystem.new(Rails.root.join("public"), prefix: "uploads/cache"),
    store: Shrine::Storage::FileSystem.new(Rails.root.join("public"), prefix: "uploads/store"),
  }

  Shrine.storages[:cache].instance_eval do
    def delete(id)
      puts path(id) # print each deleted file
      super
    end
  end
```

Shrine doesn't delete cached files by default at all, so the only thing that should trigger this deletion is the `delete_promoted` plugin.

One more thing is if you're using `Shrine::Storage::FilesSystem#clear!(older_than: some_expiration_date)` in a recurring task, it might be worth disabling it to see if it fixes the error. Now that I'm writing this, I realized that the current implementation (excluding new changes in master) of `Shrine::Storage::FilesSystem#clear!(older_than: some_expiration_date)` is much more messed up that I thought, because it `rm -r`'s old subdirectories, but I found out now that the "last modified" time of a directory doesn't get updated recursively up the stack. As we can see from the following script, only the "last modified" time of the inner-most directory is changed when a new file is created.

```rb
require "pathname"
require "tmpdir"

tmpdir = Pathname.new(Dir.tmpdir)
tmpdir.join("dir1").rmtree

tmpdir.join("dir1/dir2").mkpath # create directories
puts tmpdir.join("dir1").mtime      #=> 2017-03-30 13:31:44 +1100
puts tmpdir.join("dir1/dir2").mtime #=> 2017-03-30 13:31:44 +1100

sleep 1

FileUtils.touch tmpdir.join("dir1/dir2/file")  # create new file
puts tmpdir.join("dir1").mtime      #=> 2017-03-30 13:31:44 +1100
puts tmpdir.join("dir1/dir2").mtime #=> 2017-03-30 13:31:45 +1100

```

I fixed the implementation recently in https://github.com/janko-m/shrine/commit/eb877f8ec2288eeab1cb967e737364430bd52471, but haven't released a new version yet, though I will really hurry it up now.

**Comment by janko-m** [comment]
I will close this, since it's probably `Shrine::Storage::FilesSystem#clear!(older_than: some_expiration_date)` being called in production, and there is already a [fix](https://github.com/janko-m/shrine/commit/eb877f8ec2288eeab1cb967e737364430bd52471) on master.

**Comment by R4ttlesnake** [comment]
Hi, first of all thanks for all the help, I really appreciate it and Shrine, of course. The problem is solved, though the source was somewhere else.

I was not calling `Shrine::Storage::FilesSystem#clear!` and I tried all the recommended changes, but finally it turned out that my Sidekiq server was not restarting properly after deploying to production (I guess Sidekiq must have looked in the old release folders, not sure). Now, I'm restarting Sidekiq with a Capistrano task and Shrine's file handling with Sidekiq works well.

I hope this didn't cause to much of an inconvenience and at least helped to fix the issue with `Shrine::Storage::FilesSystem#clear!`.

_Nothing to do with Shrine, but for anybody interested: I'm starting Sidekiq via Systemd based on [this example](https://github.com/mperham/sidekiq/blob/d8f11c26518dbe967880f76fd23bb99e9d2411d5/examples/systemd/sidekiq.service). With a Capistrano task based on [this example](https://github.com/mperham/sidekiq/wiki/Deploying-to-Ubuntu), I'm restarting Sidekiq after each deployment via `sudo service sidekiq restart` (to skip sudo's password prompt, the deployment user needs permission to execute this sudo command without password)._ 

```
# lib/capistrano/tasks/sidekiq.rake

namespace :sidekiq do 
  task :quiet do
    on roles(:app) do
      puts capture("pgrep -f 'sidekiq' | xargs kill -USR1") 
    end
  end

  task :restart do
    on roles(:app) do
      execute :sudo, :service, :sidekiq, :restart 
    end
  end
end

after 'deploy:starting', 'sidekiq:quiet'
after 'deploy:reverted', 'sidekiq:restart'
after 'deploy:published', 'sidekiq:restart'
```

**Comment by janko-m** [comment]
@R4ttlesnake No worries, I'm glad it's solved 👍
