### ISSUE TITLE
 undefined method `attacher'

### ISSUE THREAD

**Issue by geniuskidkanyi** [janko-m/shrine#153]
am trying to migrate from carrierwave to shrine
i keep getting this error  undefined method `attacher'
here is the log
```
2017-03-29T12:42:34.966Z 5616 TID-gsaxg2j88 PromoteJob JID-3e7bb80757b370013e10211d INFO: start
2017-03-29T12:42:35.076Z 5616 TID-gsaxg2j88 PromoteJob JID-3e7bb80757b370013e10211d INFO: fail: 0.109 sec
2017-03-29T12:42:35.078Z 5616 TID-gsaxg2j88 WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"PromoteJob","queue":"default","args":[{"job_class":"PromoteJob","job_id":"600e6bb6-5a18-480b-83f7-343b58361d9e","queue_name":"default","arguments":[{"attachment":"{\"id\":\"fff1460dd09e80ab3c8d0ed48cfa235b.mp4\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"WHEN TRAP RAPPERS START MAKING GOSPEL MUSIC.mp4\",\"size\":6744778,\"mime_type\":\"video/mp4\"}}","record":["Post","32"],"name":"file","shrine_class":"VideoUploader","action":"store","phase":"store","_aj_symbol_keys":[]}],"locale":"en"}],"retry":true,"jid":"3e7bb80757b370013e10211d","created_at":1490790642.7649128,"enqueued_at":1490791354.9611187,"error_message":"undefined method `attacher' for #<PromoteJob:0x005623bdd25e88>","error_class":"NoMethodError","failed_at":1490791314.0595675,"retry_count":1,"retried_at":1490791355.0722985},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"PromoteJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"PromoteJob\",\"job_id\":\"600e6bb6-5a18-480b-83f7-343b58361d9e\",\"queue_name\":\"default\",\"arguments\":[{\"attachment\":\"{\\\"id\\\":\\\"fff1460dd09e80ab3c8d0ed48cfa235b.mp4\\\",\\\"storage\\\":\\\"cache\\\",\\\"metadata\\\":{\\\"filename\\\":\\\"WHEN TRAP RAPPERS START MAKING GOSPEL MUSIC.mp4\\\",\\\"size\\\":6744778,\\\"mime_type\\\":\\\"video/mp4\\\"}}\",\"record\":[\"Post\",\"32\"],\"name\":\"file\",\"shrine_class\":\"VideoUploader\",\"action\":\"store\",\"phase\":\"store\",\"_aj_symbol_keys\":[]}],\"locale\":\"en\"}],\"retry\":true,\"jid\":\"3e7bb80757b370013e10211d\",\"created_at\":1490790642.7649128,\"enqueued_at\":1490791354.9611187,\"error_message\":\"undefined method `attacher' for #<PromoteJob:0x005623bd6cbc68>\",\"error_class\":\"NoMethodError\",\"failed_at\":1490791314.0595675,\"retry_count\":0}"}
2017-03-29T12:42:35.083Z 5616 TID-gsaxg2j88 WARN: NoMethodError: undefined method `attacher' for #<PromoteJob:0x005623bdd25e88>
2017-03-29T12:42:35.084Z 5616 TID-gsaxg2j88 WARN: /home/geniuskid/rails/stories/app/jobs/promote_job.rb:5:in `perform'
/home/geniuskid/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activejob-4.2.6/lib/active_job/execution.rb:32:in `block in perform_now'
```

this my uploader class

```rb
  plugin :processing
  plugin :versions
  plugin :activerecord
  process(:store) do |data|
    mov = data.download
    video = Tempfile.new(["video", ".webm"], binmode: true)
    screenshot = Tempfile.new(["screenshot", ".png"], binmode: true)

    movie = FFMPEG::Movie.new(mov.path)
    movie.transcode(video.path)
    movie.screenshot(screenshot.path)

    mov.delete

    {video: video, screenshot: screenshot}
  end
```
while this my promte job

```rb
  def perform(data)
    # pry.binding
    attacher Shrine::Attacher.promote(data)
    attacher.record.update(status: 2) if attacher && attacher.record.is_a?(Post)
  end
```

**Comment by janko-m** [comment]
You are missing `=` in the first line of `PromoteJob#perform`, it should be 

```rb
  def perform(data)
    # pry.binding
    attacher = Shrine::Attacher.promote(data)
    attacher.record.update(status: 2) if attacher && attacher.record.is_a?(Post)
  end
```
