### ISSUE TITLE
When add backgrounding plugin it breaks controller action

### ISSUE THREAD

**Issue by prem-prakash** [janko-m/shrine#165]
```
Started GET "/conta/editar" for 127.0.0.1 at 2017-06-02 02:13:47 -0300
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by StudentsController#edit as HTML
  Student Load (0.8ms)  SELECT  "students".* FROM "students" WHERE "students"."id" = $1  ORDER BY "students"."id" ASC LIMIT 1  [["id", 50]]
  Rendered students/edit.html.erb within layouts/application (16.8ms)
Completed 500 Internal Server Error in 111ms (ActiveRecord: 4.0ms)

ActionView::Template::Error (storage :cache isn't registered on StudentProfileImageUploader):
    20:     <%= f.error_notification %>
    21:
    22:     <h5>Foto</h5>
    23:     <div class='profile-image-card mdl-card' style="background-image: url('<%= resource.profile_image_url %>')">
    24:       <div class="mdl-card__menu">
    25:         <button type="button" id="drop-menu" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
    26:           <i class="material-icons">more_vert</i>
  app/models/student.rb:90:in `profile_image_url'
  app/views/students/edit.html.erb:23:in `block in _app_views_students_edit_html_erb__1344750176787292233_70177947978740'
  app/views/students/edit.html.erb:17:in `_app_views_students_edit_html_erb__1344750176787292233_70177947978740'
  app/controllers/students_controller.rb:5:in `edit'
```

```ruby
# config/initializers/shrine.rb

require 'shrine'
require 'shrine/storage/s3'

s3_options = {
  access_key_id:     ENV.fetch('AWS_ACCESS_KEY'),
  secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
  region:            ENV.fetch('AWS_REGION'),
  bucket:            ENV.fetch('AWS_BUCKET')
}

Shrine.storages = {
  store: Shrine::Storage::S3.new(prefix: nil, **s3_options),
  cache: Shrine::Storage::S3.new(prefix: 'cache', **s3_options)
}
```

```ruby
class StudentsController < Devise::RegistrationsController
  layout 'application'

  def after_update_path_for(_resource)
    edit_student_registration_path
  end

  protected

  def update_resource(resource, params)
    if params[:password].blank?
      resource.update_without_password(params)
    else
      result = resource.update_attributes(params)
      clean_up_passwords resource
      result
    end
  end
end
```

```ruby
# app/models/student_profile_image_uploader.rb

require 'shrine'
require 'shrine/storage/s3'

class StudentProfileImageUploader < Shrine
  MAX_SIZE = 5

  plugin :activerecord
  plugin :default_storage, cache: :cache, store: :store
  plugin :default_url
  plugin :delete_promoted
  plugin :determine_mime_type
  plugin :direct_upload, allowed_storages: [:cache],
                         presign_options: {
                           acl: 'private',
                           content_length_range: 0..(MAX_SIZE * 1024 * 1024)
                         }
  plugin :logging, format: :human, logger: Rails.logger
  plugin :remove_attachment
  plugin :upload_options, cache: { acl: 'private' }, store: { acl: 'private' }
  plugin :validation_helpers
  plugin :backgrounding

  Attacher.promote { |data| AttachmentPromoteJob.perform_later(data) }
  Attacher.delete { |data| AttachmentDeleteJob.perform_later(data) }

  def generate_location(io, context = {})
    "student_profile/#{Admin::Campus.current_tenant}/#{super}"
  end

  Attacher.default_url do |_options|
    ActionController::Base.helpers.asset_path('profile-image.png')
  end

  Attacher.validate do
    validate_max_size MAX_SIZE * 1024 * 1024, message: "is too large (max is #{MAX_SIZE} MB)"
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
  end
end
```

```ruby
class AttachmentPromoteJob < ApplicationJob
  def perform(data)
    Shrine::Attacher.promote(data)
  end
end
```

```ruby
class AttachmentPromoteJob < ApplicationJob
  def perform(data)
    Shrine::Attacher.promote(data)
  end
end
```

```ruby
class AttachmentDeleteJob < ApplicationJob
  def perform(data)
    Shrine::Attacher.delete(data)
  end
end
```

```ruby
class Student < ActiveRecord::Base
  include StudentProfileImageUploader[:profile_image]
  ...
  def profile_image_url
    return ActionController::Base.helpers.asset_path('profile-image.png') if profile_image.blank?
    url = profile_image.url(public: true, host: "https://content.#{Admin::Campus.current_campus.domain}")
    Admin::Campus.production_host? ? CdnUrlSigner.generate(url) : profile_image.url
  end
end
```

if I comment these lines on StudentProfileImageUploader it works:

```ruby
  plugin :backgrounding
  Attacher.promote { |data| AttachmentPromoteJob.perform_later(data) }
  Attacher.delete { |data| AttachmentDeleteJob.perform_later(data) }
```

**Comment by prem-prakash** [comment]
Solved it changing:

```ruby
return ActionController::Base.helpers.asset_path('profile-image.png') if profile_image.blank?
```

to

```ruby
return ActionController::Base.helpers.asset_path('profile-image.png') if profile_image_data.blank?
```

don't understand but it is ok

**Comment by prem-prakash** [comment]
I found that the problem was the order of the initializers.
There was an initializer calling the model with the attachment that was being loaded before shrine.
I renamed shrine.rb to 0_shrine.rb and all problems were solved
