### ISSUE TITLE
Bug with configurations not being set during startup

### ISSUE THREAD

**Issue by kurko** [janko-m/shrine#173]
EDIT: more code in `background`

### Background

Trying to use Shrine within a Rails Engine. My setup is pretty simple:

```ruby
require 'shrine'
require "shrine/storage/s3"

s3_options = {
  access_key_id:     ENV.fetch("S3_ACCESS_KEY_ID"),
  secret_access_key: ENV.fetch("S3_SECRET_ACCESS_KEY"),
  region:            ENV.fetch("S3_REGION"),
  bucket:            ENV.fetch("S3_BUCKET"),
}
Shrine.storages = {
  cache: Shrine::Storage::S3.new(prefix: "cache", **s3_options),
  store: Shrine::Storage::S3.new(prefix: "store", **s3_options),
}

Shrine.plugin :activerecord
Shrine.plugin :direct_upload
Shrine.plugin :backgrounding

class ::FileUploader < Shrine
end

MyEngine::Engine.routes.draw do
  mount ::FileUploader::UploadEndpoint => "/files"

  # ...
end

class MyModel < ActiveRecord::Base
  include ::FileUploader[:file]
end
```

### The problem

Got the following error.

```
Started GET "/files/cache/presign?extension=.jpg&_=1499104193229" for 127.0.0.1 at 2017-07-03 14:49:53 -0300

NoMethodError (undefined method `map' for nil:NilClass
Did you mean?  tap):

shrine (2.6.1) lib/shrine/plugins/direct_upload.rb:297:in `allow_storage!'
shrine (2.6.1) lib/shrine/plugins/direct_upload.rb:226:in `get_uploader'
shrine (2.6.1) lib/shrine/plugins/direct_upload.rb:197:in `block (2 levels) in <class:App>'
```

### Investigation

I went on to investigate and found this out:

```
    165: def self.configure(uploader, opts = {})
 => 166:   require 'pry'; binding.pry
    167:   uploader.opts[:direct_upload_allowed_storages] = opts.fetch(:allowed_storages, uploader.opts.fetch(:direct_upload_allowed_storages, [:cache]))
    168:   uploader.opts[:direct_upload_presign_options] = opts.fetch(:presign_options, uploader.opts.fetch(:direct_upload_presign_options, {}))
    169:   uploader.opts[:direct_upload_presign_location] = opts.fetch(:presign_location, uploader.opts[:direct_upload_presign_location])
    170:   uploader.opts[:direct_upload_max_size] = opts.fetch(:max_size, uploader.opts[:direct_upload_max_size])
    171:
    172:   uploader.assign_upload_endpoint(App) unless uploader.const_defined?(:UploadEndpoint)
    173: end

[1] pry(Shrine::Plugins::DirectUpload)> opts.fetch(:allowed_storages, uploader.opts.fetch(:direct_upload_allowed_storages, [:cache]))
[
    [0] :cache
]

    297: def allow_storage!(storage_key)
 => 298:   require 'pry'; binding.pry
    299:   if !allowed_storages.map(&:to_s).include?(storage_key)
    300:     error! 403, "Storage #{storage_key.inspect} is not allowed."
    301:   end
    302: end

[1] pry(#<FileUploader::UploadEndpoint>)> show-method allowed_storages
def allowed_storages
  shrine_class.opts[:direct_upload_allowed_storages]
end
[2] pry(#<FileUploader::UploadEndpoint>)> uploader
nil
[3] pry(#<FileUploader::UploadEndpoint>)> shrine_class.opts
{}
```

**Conclusion:** although config is being set on initialization, `shrine_class.opts` is empty.

I'm using Shrine in another Rails app (but not within an Engine) and it's working fine.

Any idea what it could be before I dig deeper?

**Comment by kurko** [comment]
Investigated further and found out the culprit. My `FileUploader` class had `require_dependency('shrine')` at the beginning of the file. When I removed it it worked.

I found out that on initialization, `p Shrine.storages` returned `[:cache, :store]` as expected. However on my uploader file it was empty. Somewhere when Shrine is loaded the storages are reset.
