### ISSUE TITLE
IOError - closed stream when using determine_mime_type plugin

### ISSUE THREAD

**Issue by Xosmond** [janko-m/shrine#201]
Hello, I have this error when I add the determine_mime_type plugin to my uploader. I think that determine_mime_type is closing the file?

Error trace:
```
IOError - closed stream:
  /Users/user/.rbenv/versions/2.3.5/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
  actionpack (5.1.4) lib/action_dispatch/http/upload.rb:78:in `eof?'
  shrine (2.8.0) lib/shrine/plugins/determine_mime_type.rb:138:in `call'
  shrine (2.8.0) lib/shrine/plugins/determine_mime_type.rb:90:in `determine_mime_type'
  shrine (2.8.0) lib/shrine/plugins/determine_mime_type.rb:117:in `extract_mime_type'
  shrine (2.8.0) lib/shrine.rb:265:in `extract_metadata'
  shrine (2.8.0) lib/shrine.rb:358:in `get_metadata'
  shrine (2.8.0) lib/shrine.rb:300:in `_store'
  shrine (2.8.0) lib/shrine/plugins/versions.rb:190:in `_store'
  shrine (2.8.0) lib/shrine.rb:233:in `store'
  shrine (2.8.0) lib/shrine/plugins/hooks.rb:95:in `block in store'
  shrine (2.8.0) lib/shrine/plugins/hooks.rb:101:in `around_store'
  shrine (2.8.0) lib/shrine/plugins/hooks.rb:95:in `store'
  shrine (2.8.0) lib/shrine/plugins/logging.rb:86:in `block in store'
  shrine (2.8.0) lib/shrine/plugins/logging.rb:101:in `block in log'
  shrine (2.8.0) lib/shrine/plugins/logging.rb:161:in `benchmark'
  shrine (2.8.0) lib/shrine/plugins/logging.rb:101:in `log'
  shrine (2.8.0) lib/shrine/plugins/logging.rb:86:in `store'
  shrine (2.8.0) lib/shrine.rb:211:in `upload'
  shrine (2.8.0) lib/shrine/plugins/hooks.rb:56:in `block in upload'
  shrine (2.8.0) lib/shrine/plugins/hooks.rb:62:in `around_upload'
  shrine (2.8.0) lib/shrine/plugins/hooks.rb:56:in `upload'
  shrine (2.8.0) lib/shrine.rb:629:in `cache!'
  shrine (2.8.0) lib/shrine.rb:520:in `assign'
  shrine (2.8.0) lib/shrine.rb:411:in `image='
  activemodel (5.1.4) lib/active_model/attribute_assignment.rb:46:in `_assign_attribute'
  activemodel (5.1.4) lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
  activemodel (5.1.4) lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
  activerecord (5.1.4) lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
  activemodel (5.1.4) lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
  activerecord (5.1.4) lib/active_record/persistence.rb:284:in `block in update'
  activerecord (5.1.4) lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
  activerecord (5.1.4) lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
  activerecord (5.1.4) lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
  /Users/user/.rbenv/versions/2.3.5/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (5.1.4) lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
  activerecord (5.1.4) lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
  activerecord (5.1.4) lib/active_record/transactions.rb:210:in `transaction'
  activerecord (5.1.4) lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
  activerecord (5.1.4) lib/active_record/persistence.rb:283:in `update'
  app/controllers/products_controller.rb:77:in `update'
  actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  actionpack (5.1.4) lib/abstract_controller/base.rb:186:in `process_action'
  actionpack (5.1.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (5.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (5.1.4) lib/active_support/callbacks.rb:131:in `run_callbacks'
  actionpack (5.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.1.4) lib/action_controller/metal/rescue.rb:20:in `process_action'
  actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument'
  activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument'
  actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (5.1.4) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
  searchkick (2.3.2) lib/searchkick/logging.rb:209:in `process_action'
  activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
  actionpack (5.1.4) lib/abstract_controller/base.rb:124:in `process'
  actionview (5.1.4) lib/action_view/rendering.rb:30:in `process'
  actionpack (5.1.4) lib/action_controller/metal.rb:189:in `dispatch'
  actionpack (5.1.4) lib/action_controller/metal.rb:253:in `dispatch'
  actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
  actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:31:in `serve'
  actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
  actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
  actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
  apartment (2.0.0) lib/apartment/elevators/generic.rb:21:in `block in call'
  apartment (2.0.0) lib/apartment/adapters/abstract_adapter.rb:85:in `switch'
  /Users/user/.rbenv/versions/2.3.5/lib/ruby/2.3.0/forwardable.rb:204:in `switch'
  apartment (2.0.0) lib/apartment/elevators/generic.rb:21:in `call'
  bullet (5.6.1) lib/bullet/rack.rb:10:in `call'
  apartment (2.0.0) lib/apartment/reloader.rb:18:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (2.0.3) lib/rack/etag.rb:25:in `call'
  rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
  rack (2.0.3) lib/rack/head.rb:12:in `call'
  rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
  rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
  actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  activerecord (5.1.4) lib/active_record/migration.rb:556:in `call'
  actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
  activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
  actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
  actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
  web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
  web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
  actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
  activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
  railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
  sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
  rack (2.0.3) lib/rack/method_override.rb:22:in `call'
  rack (2.0.3) lib/rack/runtime.rb:22:in `call'
  activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
  actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
  rack-cache (1.6.1) lib/rack/cache/context.rb:140:in `forward'
  rack-cache (1.6.1) lib/rack/cache/context.rb:147:in `pass'
  rack-cache (1.6.1) lib/rack/cache/context.rb:159:in `invalidate'
  rack-cache (1.6.1) lib/rack/cache/context.rb:74:in `call!'
  rack-cache (1.6.1) lib/rack/cache/context.rb:51:in `call'
  actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
  rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
  sentry-raven (2.6.3) lib/raven/integrations/rack.rb:50:in `call'
  railties (5.1.4) lib/rails/engine.rb:522:in `call'
  puma (3.10.0) lib/puma/configuration.rb:225:in `call'
  puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
  puma (3.10.0) lib/puma/server.rb:437:in `process_client'
  puma (3.10.0) lib/puma/server.rb:301:in `block in run'
  puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

And the uploader:
```ruby
require "image_processing/mini_magick"
class ImageUploader < Shrine
  include ImageProcessing::MiniMagick
  plugin :processing
  plugin :versions
  plugin :cached_attachment_data
  plugin :determine_mime_type

  process(:store) do |io, context|
      { original: io, medium: resize_to_limit!(io.download, 600, 600), small: resize_to_limit!(io.download, 300, 300), thumb: resize_to_limit!(io.download, 100, 100) }
  end

  Attacher.validate do
    validate_max_size 3.megabyte, message: "is too large (max is 3 MB)"
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg', 'image/png']
  end

  def generate_location(io, context)
    model_name  = context[:record].class.name.downcase if context[:record]
    if context[:version] == :original
      style = "originals"
    elsif context[:version] == :medium
      style = "mediums"
    elsif context[:version] == :small
      style = "smalls"
    else
      style = "thumbs"
    end
    id = context[:record].id
    name  = super
    [model_name, id, "images", style, name].compact.join("/")
  end
end
```

**Comment by janko-m** [comment]
The `determine_mime_type` plugin is not closing given IO objects. Can you verify that the original file assigned to the Shrine attachment attribute is not already closed to begin with? See https://github.com/janko-m/shrine/issues/107 for more context on why I'm asking that. You can do that by retrieving the `ActionDispatch::Http::UploadedFile` object from params in the controller and calling `#closed?` on it and printing out the result.

**Comment by Xosmond** [comment]
The problem was this code on my controller:
```ruby
@product.assign_attributes product_params
## some code
@product.update product_params
```

Now I have changed to:
```ruby
@product.assign_attributes product_params
## some code
@product.save
```

Looks like the temp file got closed on assign_attributes method. By the way, this error only happens when I add the `determine_mime_type` plugin. So, before that, I was assigning the file already closed and no error was raised. Is that ok for Shrine?

**Comment by janko-m** [comment]
>  So, before that, I was assigning the file already closed and no error was raised. Is that ok for Shrine?

Shrine is not expected to handle closed IO objects, any give IO objects should be open.

I don't know why Shrine didn't raise an exception when the closed file was supposed to get uploaded to storage. The `determine_mime_type` plugin calls `#read` on the IO object, so if that IO object is closed, `IOError: closed stream` exception will be raised.

You have to make sure not to close the `ActionDispatch::Http::UploadedFile` before giving it to Shrine.
