### ISSUE TITLE
Can't presign with options

### ISSUE THREAD

**Issue by hakunin** [janko-m/shrine#43]
Hi, I am unable to use presigned request with additional options.

Using `pry` I open up the code on where it fails and its this line from direct upload plugin:

```
signature = @uploader.storage.presign(location, options || {})
```

Looking at what  is there:
```
> [location, options]
["0042c4091bed9e492c5d54be2c92ffe38a4a6049f68e282eb3f0d0db5bfd/${filename}", {"success_action_redirect"=>"/api/uploads/callback?parent_id=1386&parent_type=Card"}]
```

This is the error that I get:

```
> signature = @uploader.storage.presign(location, options || {})
Wrong number of arguments (2 for 1)
===================================
[0] /vendor/gems/shrine-1.2.0/lib/shrine/storage/s3.rb:206:in `presign'
    201:       # Returns a signature for direct uploads. Internally it calls
    202:       # [`Aws::S3::Bucket#presigned_post`], and forwards any additional options
    203:       # to it.
    204:       #
    205:       # [`Aws::S3::Bucket#presigned_post`]: http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Bucket.html#presigned_post-instance_method
 => 206:       def presign(id, **options)
    207:         options = upload_options.merge(options)
    208:         object(id).presigned_post(options)
    209:       end
    210: 
    211:       protected
[21] /vendor/gems/shrine-1.2.0/lib/shrine/plugins/direct_upload.rb:195:in `block (3 levels) in <class:App>'
[25] /vendor/gems/shrine-1.2.0/lib/shrine/plugins/direct_upload.rb:191:in `block (2 levels) in <class:App>'
[28] /vendor/gems/shrine-1.2.0/lib/shrine/plugins/direct_upload.rb:180:in `block in <class:App>'
```

When the second argument is empty:
```
> [location, options]
["2376793e32b3fc1874ca9e578e9698725e555bdeb4792d39bb0fd73513f3/${filename}", {}]
```

it passes fine.
```
> signature = @uploader.storage.presign(location, options || {})
=> #<Aws::S3::PresignedPost:0x007fbbf0c35858
 @bucket_name="......",
 @bucket_region="eu-central-1",
 @conditions=[{"bucket"=>"....."}, ["starts-with", "$key", "cache/39dc821e56780a10c513a5e37a45c64b9f7c9945e0825d11ab96c44f5bff/"]],
 @credentials=#<Aws::Credentials access_key_id=".........">,
 @fields={"key"=>"cache/39dc821e56780a10c513a5e37a45c64b9f7c9945e0825d11ab96c44f5bff/${filename}"},
 @key_set=true,
 @signature_expiration=2016-02-08 11:31:01 +0100,
 @url="https://mozek.s3.eu-central-1.amazonaws.com">
```

I was looking into how the keyword arguments method work and couldn't find anything wrong with shrine's code. 

I checked the method's arity, and its -2, which means 1 required argument and variable more. Which makes sense when looking at the code, but not when looking at the behavior.

Also tried calling it with `**options`, but no luck:
```
> signature = @uploader.storage.presign(location, **(options || {}))
Wrong argument type string (expected symbol)
============================================
[20] /vendor/gems/shrine-1.2.0/lib/shrine/plugins/direct_upload.rb:195:in `block (3 levels) in <class:App>'
    190: 
    191:             r.get "presign" do
    192:               location = SecureRandom.hex(30) + request.params["extension"].to_s
    193:               options = presign.call(request) if presign.respond_to?(:call)
    194: 
 => 195:               binding.pry
    196:               signature = @uploader.storage.presign(location, **(options || {}))
    197: 
    198:               json Hash[url: signature.url, fields: signature.fields]
    199:             end if presign
    200:           end
[24] /vendor/gems/shrine-1.2.0/lib/shrine/plugins/direct_upload.rb:191:in `block (2 levels) in <class:App>'
[27] /vendor/gems/shrine-1.2.0/lib/shrine/plugins/direct_upload.rb:180:in `block in <class:App>'
```

I am using Ruby 2.1.5, but also tested with 2.2.1.

Any ideas?

**Comment by janko-m** [comment]
Keyword arguments only work with hashes that have symbolized keys. You're hash has a string key, so Ruby doesn't recognize it as a hash of keyword parameters. I assume it's coming from Rails' `params` hash, which is a `HashWithIndifferentAccess`, but internally it's stored as a stringified hash. So, the `options` variable should be a pure `Hash` object equal to `{success_action_redirect: "/api/uploads/callback?parent_id=1386&parent_type=Card"}`.

**Comment by hakunin** [comment]
Ahh, thanks!
