### ISSUE TITLE
_enforce_io doesn't work with method_missing

### ISSUE THREAD

**Issue by zlobz** [janko-m/shrine#67]
```
     NameError:
       undefined method `read' for class `Rack::Test::UploadedFile'
     # /home/_/.bundle/ruby/2.3.0/shrine-9c7ff26556fa/lib/shrine.rb:364:in `method'
     # /home/_/.bundle/ruby/2.3.0/shrine-9c7ff26556fa/lib/shrine.rb:364:in `block in _enforce_io'
```
Rack::Test::UploadedFile source:
https://github.com/brynary/rack-test/blob/master/lib/rack/test/uploaded_file.rb
```ruby
      def method_missing(method_name, *args, &block) #:nodoc:
        @tempfile.__send__(method_name, *args, &block)
      end

      def respond_to?(method_name, include_private = false) #:nodoc:
        @tempfile.respond_to?(method_name, include_private) || super
      end
```
### Solution:
Do not check method parameters.
Remove this check: `&& [a.count, -1].include?(io.method(m).arity)`

**Comment by janko-m** [comment]
Thank you for reporting, this is definitely an unexpected result of the current behaviour, I will remove the parameter checking.
